proxy:
    image: amouat/proxy:1.0
    links:
        - identidock
    ports:
        - "80:80"
    environment:
        - NGINX_HOST=192.168.0.154
        - NGINX_PROXY=http://identidock:9090
identidock:
    image: amouat/identidock:1.0
    environment:
        ENV: PROD
    links:
        - dnmonster
        - redis
dnmonster:
    image: amouat/dnmonster:1.0
redis:
    image: redis:3
logspout:
    image: amouat/logspout-logstash
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
    ports:
        - "8000:80"
    links:
        - logstash
    command: logstash://logstash:5000
logstash:
    image: logstash
    volumes:
        - ./logstash.conf:/etc/logstash.conf
    environment:
        LOGSPOUT: ignore
    links:
        - elasticsearch
    command: -f /etc/logstash.conf
elasticsearch:
    image: elasticsearch:1.7
    environment:
        LOGSPOUT: ignore
kibana:
    image: kibana:4
    environment:
        LOGSPOUT: ignore
        ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
        - elasticsearch
    ports:
        - "5601:5601"

